### PR TITLE
Hotfix/us states

### PR DESCRIPTION
**Pull request by sreyemnayr**
Finally got it working!  There was a missing field address_country that was causing problems!

### CODE REVIEW

**Comment by sreyemnayr** [comment]
Sorry, I should have opened a new branch

**Comment by lukeburden** [comment]
I'll add country to the form - I'll leave this PR alone as it contains changes from your previous PR.

**Comment by sreyemnayr** [comment]
Yeah I haven't ever really done the pull request thing before, sorry about that!

Ryan Meyers
________________________________

**Comment by lukeburden** [comment]
No problem! Always best with a clean branch of your own with your changes squashed and rebased off of the origin and branch location where you're trying to have your changes accepted.

**Comment by lukeburden** [comment]
I've pushed that to HEAD of the `connect` branch - let me know if that doesn't work for you.

**Pull request closed without merging**
