### PR TITLE
Fixups for Connect

### PR DESCRIPTION
**Pull request by blueyed**
Those should be applied using `git rebase -i --autosquash` (in the end).

### CODE REVIEW

**Comment by blueyed** [comment]
JFI: it was not meant to be squash-merged here, but get applied when autosquashing later.

**Comment by lukeburden** [comment]
@blueyed noted, wasn't familiar with that workflow. Just [read a little](https://robots.thoughtbot.com/autosquashing-git-commits) and shall heed next time.

**Comment by blueyed** [comment]
Cool, although I've mentioned the `git rebase --interactive --autosquash` especially.. ;)

**Comment by blueyed** [comment]
Thanks for picking them anyway!

**Pull request merged**
